[project]
name = 'Alcaraz'
description = 'Demonstrates a basic fungible token that conforms to Alcaraz tennis player'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP1AJVMEGSMD6QCSZ1669Z5G90GEHVK2MEM7J0AHH.alcaraz'

[contracts.alcaraz]
path = 'contracts/alcaraz.clar'
clarity_version = 4
epoch = "latest"

[contracts.defi]
path = 'contracts/extern/defi.clar'
clarity_version = 4
epoch = "latest"

